FROM php:8.3-fpm

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install system dependencies
RUN apt-get update --fix-missing
RUN apt-get install -y git curl libpng-dev libonig-dev libxml2-dev libzip-dev libjpeg-dev libpng-dev unzip nano mc 

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

###add any installs here
#RUN pecl install redis && docker-php-ext-enable redis

#Postgres
#RUN apt-get install -y libpq-dev && docker-php-ext-install pdo pdo_pgsql

#Xdebug | https://matthewsetter.com/setup-step-debugging-php-xdebug3-docker/
#RUN pecl install xdebug && docker-php-ext-enable xdebug

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

# Set working directory
WORKDIR /var/www

USER $user
